apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: valloxmqtt
  annotations:
    github.com/project-slug: tkekkone/valloxmqtt
spec:
  type: other
  lifecycle: unknown
  owner: guests
